# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_inversions <- function(x) {
    .Call(`_rankr_count_inversions`, x)
}

#' Estimate variants of Kendall's tau
#'
#' @param x,y Vectors of observations.
#' @return The variant of Kendall's tau.
#' @export
#' @name tau
tau_a <- function(x, y) {
    .Call(`_rankr_tau_a`, x, y)
}

#' @rdname tau
#' @export
tau_b <- function(x, y) {
    .Call(`_rankr_tau_b`, x, y)
}

#' @rdname tau
#' @export
tau_c <- function(x, y) {
    .Call(`_rankr_tau_c`, x, y)
}

#' @rdname tau
#' @export
tau_d <- function(x, y) {
    .Call(`_rankr_tau_d`, x, y)
}

#' @rdname tau
#' @export
somers_d <- function(x, y) {
    .Call(`_rankr_somers_d`, x, y)
}

#' @rdname tau
#' @export
gk_gamma <- function(x, y) {
    .Call(`_rankr_gk_gamma`, x, y)
}

